version: "3"

services:
  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend-intro
    volumes:
      - backend_intro_db:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    build:
      context: .
    depends_on:
      - db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/backend-intro
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      PORT: 8080
    ports:
      - "8080:8080"
    restart: on-failure
volumes:
  backend_intro_db:
