FROM hasura/graphql-engine:latest

#COPY ./migrations /hasura-migrations
#COPY ./metadata /hasura-metadata

ENV HASURA_GRAPHQL_ENABLE_CONSOLE=true
ENV HASURA_GRAPHQL_CLI_ENVIRONMENT=default
ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
ENV HASURA_GRAPHQL_DATABASE_URL=HASURA_GRAPHQL_DATABASE_URL
ENV HASURA_GRAPHQL_ADMIN_SECRET=HASURA_GRAPHQL_ADMIN_SECRET

CMD graphql-engine --database-url $HASURA_GRAPHQL_DATABASE_URL serve --server-port 8080
